<?php

return [
    // The Telegram BOT api token
    'token' => env('TELEGRAM_TOKEN'),

    // if the webhook mode must validate the incoming IP range is from a telegram server
    'safe_mode' => true,

    // Extra or specific configurations
    'config' => [
        'api_url' => 'https://api.telegram.org', // или локальный сервер
        'enable_http2' => true,
        'bot_name' => null,                     // нужен для группового бота
        'is_local' => true,                     // true при self-hosted Bot API
        'test_env' => true,                    // true при тестировании Web Apps
        'client_timeout' => 5,                  // таймаут запросов к Telegram API (сек)
        'conversation_ttl' => 43200,            // TTL conversations (сек), null = бессрочно

        'client_options' => [],                 // доп. опции для Guzzle

        'polling' => [
            'timeout' => 10,
            'limit' => 100,
            'allowed_updates' => [],     // пусто = все типы апдейтов
        ],
    ],

    // Set if the service provider should automatically load
    // handlers from /routes/telegram.php
    'routes' => true,

    // Enable or disable Nutgram mixins
    'mixins' => false,

    // Path to save files generated by nutgram:make command
    'namespace' => app_path('Telegram'),

    // Set log channel
    'log_channel' => env('TELEGRAM_LOG_CHANNEL', 'null'),
];
